### ISSUE TITLE
IsotropicTVRegulariser  in parameter.py is incorrect due to typo

### ISSUE THREAD

**Issue by idc9** [airlab-unibas/airlab#2]
[line 86](https://github.com/airlab-unibas/airlab/blob/e6e5ae975411eabed05835164adc2314f56e813d/airlab/regulariser/parameter.py#L86) of IsotropicTVRegulariser's _regulariser_2d function in `parameter.py` is missing a `:`

It currently reads
```python
(parameter[:, 1:, 1:] - parameter[:, -1, 1:]).pow(2)*self._scaling[0]
```
when it should read
```python
(parameter[:, 1:, 1:] - parameter[:, :-1, 1:]).pow(2)*self._scaling[0]
```
The same typo appears in line [94](https://github.com/airlab-unibas/airlab/blob/master/airlab/regulariser/parameter.py#L94) of _regulariser_3d.  Note this is implemented correctly in the displacement regularizer class (e.g. [see line 58](https://github.com/airlab-unibas/airlab/blob/master/airlab/regulariser/displacement.py#L58)).

# Test case

You can check this using the following simple test case and the formula on page 3 from [this paper](https://arxiv.org/pdf/1412.0035.pdf) where the answer should be `2 * sqrt(10)`

```python
X = np.array([[0, 1, 2], [3, 4, 5]])
T = torch.from_numpy(X).unsqueeze(0).float()

def current_incorrect(T):
    dx = (T[:, 1:, 1:] - T[:, -1, 1:]).pow(2)
    dy = (T[:, 1:, 1:] - T[:, 1:, :-1]).pow(2)
    return torch.sqrt(dx + dy).sum()


def correct_isotropic_TV(T):
    dx = (T[:, 1:, 1:] - T[:, :-1, 1:]).pow(2)
    dy = (T[:, 1:, 1:] - T[:, 1:, :-1]).pow(2)
    return torch.sqrt(dx + dy).sum()
```

```python
np.allclose(current_incorrect(T).data.numpy(), 2*np.sqrt(10))
False
```

```python
np.allclose(correct_isotropic_TV(T).data.numpy(), 2*np.sqrt(10))
True
```

**Comment by RobinSandkuehler** [comment]
Thank you very much. We fixed it.
