### ISSUE TITLE
Mutual Information loss H

### ISSUE THREAD

**Issue by connorlee77** [airlab-unibas/airlab#25]
Can you be a bit more transparent about how you calculate the mutual information loss? Particularly H. How did you guys calculate the joint histogram?

**Comment by ekhahniii** [comment]
Hello, I too am curious about the formulation for calculating the joint histogram. Maybe you could comment a bit on the motivation for this [line](https://github.com/airlab-unibas/airlab/blob/80c9d487c012892c395d63c6d937a67303c321d1/airlab/loss/pairwise.py#L381):

`p_joint = th.mm(p_f, p_m.transpose(0, 1)).div(self._normalizer_2d)`

@ChristophJud @RobinSandkuehler

**Comment by connorlee77** [comment]
@ekhahniii the histograms are calculated via kernel density estimation. If you write out the multivariate version with a gaussian kernel, you'll notice you can decompose it into the product of two univariate kernels (ignoring any scaling terms). The matrix multiply operation combines this product as well as the summation.
