### ISSUE TITLE
Registration doesn't accept verbose as a parameter, must set _verbose manually

### ISSUE THREAD

**Issue by bsugerman** [airlab-unibas/airlab#7]
When I create a new registration instance, the parameter "verbose" is rejected because it doesn't show up in the class definition. Example:

    registration = al.PairwiseRegistration(dtype=fixed_image.dtype,
                                           device=fixed_image.device, verbose=True)
yields

    TypeError: __init__() got an unexpected keyword argument 'verbose'

However, I can manually set it after defining the instance with

    registration._verbose=verbose

Figured you would want to know about this.

**Comment by RobinSandkuehler** [comment]
Hi, 
Thank you very much for the report. 
It should be fixed now.
